"""
customer_analysis.py
--------------------
Customer-level analytics including RFM (Recency-Frequency-Monetary) segmentation.

Methodology
-----------
RFM is computed from the Orders table:
  Recency   : days since the customer's most recent order
              (reference = one day after the dataset's last Order_Date)
  Frequency : number of distinct Order IDs for that customer
  Monetary  : total revenue (Sales) generated by the customer

Each dimension is scored 1-4 (quartile-based, 4 = best).
Segments are derived from the combined RFM score using simple business rules.

Limitations
-----------
* The Superstore dataset spans ~4 years (2023-2026).  With 804 customers
  and ~5 000 orders, some customers will naturally appear low-frequency
  simply because they are new.
* RFM scores here are relative within this dataset — they do not represent
  absolute loyalty or lifetime value.
* We use quartile cuts; ties are handled by Pandas' qcut duplicate-label
  handling (duplicates='drop').  This may result in unequal segment sizes.
"""

from pathlib import Path
from datetime import timedelta

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick
import seaborn as sns
import pandas as pd
import numpy as np

FIGURES_DIR = Path("outputs/figures")
FIGURES_DIR.mkdir(parents=True, exist_ok=True)

sns.set_theme(style="whitegrid", palette="muted", font_scale=1.1)


def _save(fig, filename: str) -> Path:
    path = FIGURES_DIR / filename
    fig.savefig(path, bbox_inches="tight", dpi=120)
    plt.close(fig)
    return path


# ---------------------------------------------------------------------------
# Customer-level aggregation
# ---------------------------------------------------------------------------

def customer_revenue_table(df: pd.DataFrame) -> pd.DataFrame:
    """
    Return one row per customer with aggregated Sales, Profit, Orders, Quantity.
    """
    cust = (
        df.groupby(["Customer_ID", "Customer_Name", "Segment"])
        .agg(
            Total_Sales=("Sales", "sum"),
            Total_Profit=("Profit", "sum"),
            Total_Orders=("Order_ID", "nunique"),
            Total_Quantity=("Quantity", "sum"),
        )
        .reset_index()
    )
    cust["Profit_Margin"] = cust["Total_Profit"] / cust["Total_Sales"]
    cust["Avg_Order_Value"] = cust["Total_Sales"] / cust["Total_Orders"]
    return cust.sort_values("Total_Sales", ascending=False).reset_index(drop=True)


# ---------------------------------------------------------------------------
# RFM computation
# ---------------------------------------------------------------------------

def compute_rfm(df: pd.DataFrame) -> pd.DataFrame:
    """
    Compute Recency, Frequency, and Monetary value for each customer.

    Returns
    -------
    pd.DataFrame with columns:
        Customer_ID, Customer_Name, Segment,
        Recency, Frequency, Monetary,
        R_Score, F_Score, M_Score, RFM_Score,
        RFM_Segment
    """
    snapshot_date = df["Order_Date"].max() + timedelta(days=1)

    rfm = (
        df.groupby(["Customer_ID", "Customer_Name", "Segment"])
        .agg(
            Recency=("Order_Date", lambda x: (snapshot_date - x.max()).days),
            Frequency=("Order_ID", "nunique"),
            Monetary=("Sales", "sum"),
        )
        .reset_index()
    )

    # Score each dimension 1–4 using quartile cuts.
    # Recency: lower is better → invert scoring (4 = most recent).
    # Frequency & Monetary: higher is better → 4 = highest.

    def safe_qcut(series: pd.Series, labels) -> pd.Series:
        """qcut with fallback for too-few unique values."""
        try:
            return pd.qcut(series, q=4, labels=labels, duplicates="drop")
        except ValueError:
            # If fewer than 4 distinct values exist, rank-based cut
            return pd.qcut(series.rank(method="first"), q=4, labels=labels, duplicates="drop")

    rfm["R_Score"] = safe_qcut(rfm["Recency"], labels=[4, 3, 2, 1])  # low recency days = 4
    rfm["F_Score"] = safe_qcut(rfm["Frequency"], labels=[1, 2, 3, 4])
    rfm["M_Score"] = safe_qcut(rfm["Monetary"], labels=[1, 2, 3, 4])

    # Convert to int for arithmetic
    rfm["R_Score"] = rfm["R_Score"].astype(int)
    rfm["F_Score"] = rfm["F_Score"].astype(int)
    rfm["M_Score"] = rfm["M_Score"].astype(int)

    rfm["RFM_Score"] = rfm["R_Score"] + rfm["F_Score"] + rfm["M_Score"]

    rfm["RFM_Segment"] = rfm["RFM_Score"].apply(_assign_segment)
    return rfm.sort_values("Monetary", ascending=False).reset_index(drop=True)


def _assign_segment(score: int) -> str:
    """
    Map combined RFM score (3-12) to a business-friendly segment label.

    Thresholds are set conservatively to reflect that this is a retail
    dataset and "Champions" represent the genuinely top-scoring customers.
    """
    if score >= 11:
        return "Champions"
    elif score >= 9:
        return "Loyal Customers"
    elif score >= 7:
        return "Potential Loyalists"
    elif score >= 5:
        return "At Risk"
    else:
        return "Lost / Inactive"


# ---------------------------------------------------------------------------
# Figures
# ---------------------------------------------------------------------------

def plot_top_customers_by_revenue(df: pd.DataFrame, n: int = 15) -> Path:
    cust = customer_revenue_table(df).head(n)
    fig, ax = plt.subplots(figsize=(9, 6))
    sns.barplot(data=cust, x="Total_Sales", y="Customer_Name",
                hue="Customer_Name", palette="Blues_r", legend=False, ax=ax)
    ax.set_xlabel("Total Sales (USD)")
    ax.set_ylabel("")
    ax.set_title(f"Top {n} Customers by Total Revenue")
    ax.xaxis.set_major_formatter(mtick.FuncFormatter(lambda x, _: f"${x/1e3:.0f}k"))
    plt.tight_layout()
    return _save(fig, "top_customers_revenue.png")


def plot_customer_revenue_distribution(df: pd.DataFrame) -> Path:
    cust = customer_revenue_table(df)
    fig, ax = plt.subplots(figsize=(8, 4))
    ax.hist(cust["Total_Sales"], bins=40, color="#2563eb", edgecolor="white", linewidth=0.4)
    ax.set_xlabel("Total Revenue per Customer (USD)")
    ax.set_ylabel("Number of Customers")
    ax.set_title("Customer Revenue Distribution")
    ax.xaxis.set_major_formatter(mtick.FuncFormatter(lambda x, _: f"${x/1e3:.0f}k"))
    plt.tight_layout()
    return _save(fig, "customer_revenue_distribution.png")


def plot_rfm_segments(rfm: pd.DataFrame) -> Path:
    seg_counts = rfm["RFM_Segment"].value_counts().reset_index()
    seg_counts.columns = ["Segment", "Count"]
    order = ["Champions", "Loyal Customers", "Potential Loyalists", "At Risk", "Lost / Inactive"]
    seg_counts["Segment"] = pd.Categorical(seg_counts["Segment"], categories=order, ordered=True)
    seg_counts = seg_counts.sort_values("Segment")

    palette = {"Champions": "#16a34a", "Loyal Customers": "#22d3ee",
               "Potential Loyalists": "#a3e635", "At Risk": "#f97316",
               "Lost / Inactive": "#ef4444"}

    fig, ax = plt.subplots(figsize=(8, 4))
    sns.barplot(data=seg_counts, x="Segment", y="Count",
                hue="Segment",
                palette={s: palette[s] for s in seg_counts["Segment"] if s in palette},
                legend=False, ax=ax)
    ax.set_title("RFM Customer Segments")
    ax.set_xlabel("")
    ax.set_ylabel("Number of Customers")
    plt.tight_layout()
    return _save(fig, "rfm_segments.png")


def plot_rfm_scatter(rfm: pd.DataFrame) -> Path:
    """Frequency vs Monetary scatter, coloured by Recency."""
    fig, ax = plt.subplots(figsize=(8, 5))
    sc = ax.scatter(
        rfm["Frequency"], rfm["Monetary"],
        c=rfm["Recency"], cmap="RdYlGn_r",
        alpha=0.65, s=40, edgecolors="none",
    )
    plt.colorbar(sc, ax=ax, label="Recency (days since last order)")
    ax.set_xlabel("Purchase Frequency (# orders)")
    ax.set_ylabel("Monetary Value (USD)")
    ax.set_title("RFM Scatter: Frequency vs Monetary (colour = Recency)")
    ax.yaxis.set_major_formatter(mtick.FuncFormatter(lambda x, _: f"${x/1e3:.0f}k"))
    plt.tight_layout()
    return _save(fig, "rfm_scatter.png")


def plot_segment_revenue(rfm: pd.DataFrame) -> Path:
    seg_rev = rfm.groupby("RFM_Segment")["Monetary"].sum().reset_index()
    fig, ax = plt.subplots(figsize=(8, 4))
    sns.barplot(data=seg_rev, x="RFM_Segment", y="Monetary",
                hue="RFM_Segment", palette="Blues_d", legend=False, ax=ax)
    ax.set_title("Total Revenue by RFM Segment")
    ax.yaxis.set_major_formatter(mtick.FuncFormatter(lambda x, _: f"${x/1e3:.0f}k"))
    ax.set_xlabel("")
    plt.tight_layout()
    return _save(fig, "segment_revenue.png")


def run_customer_analysis(df: pd.DataFrame) -> dict:
    """Run full customer analytics pipeline and save all figures."""
    print("[customer_analysis] Computing customer metrics...")
    cust_table = customer_revenue_table(df)
    rfm = compute_rfm(df)

    plot_top_customers_by_revenue(df)
    plot_customer_revenue_distribution(df)
    plot_rfm_segments(rfm)
    plot_rfm_scatter(rfm)
    plot_segment_revenue(rfm)

    print("[customer_analysis] Customer analysis complete.")
    return {"customer_table": cust_table, "rfm": rfm}
