-- ============================================================
-- business_analysis.sql
-- Superstore Retail Analytics — Business SQL Queries
-- ============================================================
-- Database  : data/processed/superstore.db  (SQLite)
-- Table     : orders
-- Generated by: src/database.py (run via pipeline.py or directly)
-- ============================================================


-- ------------------------------------------------------------
-- Q1. Total Sales and Profit by Category
-- Understanding which product category drives the most value.
-- ------------------------------------------------------------
SELECT
    Category,
    ROUND(SUM(Sales), 2)                         AS Total_Sales,
    ROUND(SUM(Profit), 2)                        AS Total_Profit,
    COUNT(DISTINCT Order_ID)                     AS Order_Count,
    ROUND(SUM(Profit) / SUM(Sales) * 100, 2)     AS Profit_Margin_Pct
FROM orders
GROUP BY Category
ORDER BY Total_Sales DESC;


-- ------------------------------------------------------------
-- Q2. Monthly Sales Trend
-- Identifies seasonality and growth patterns over time.
-- ------------------------------------------------------------
SELECT
    strftime('%Y-%m', Order_Date)  AS Year_Month,
    ROUND(SUM(Sales), 2)           AS Monthly_Sales,
    ROUND(SUM(Profit), 2)          AS Monthly_Profit
FROM orders
GROUP BY Year_Month
ORDER BY Year_Month;


-- ------------------------------------------------------------
-- Q3. Regional Performance
-- Which region contributes the most and is most profitable?
-- ------------------------------------------------------------
SELECT
    Region,
    ROUND(SUM(Sales), 2)                         AS Total_Sales,
    ROUND(SUM(Profit), 2)                        AS Total_Profit,
    COUNT(DISTINCT Order_ID)                     AS Orders,
    COUNT(DISTINCT Customer_ID)                  AS Customers,
    ROUND(SUM(Profit) / SUM(Sales) * 100, 2)     AS Profit_Margin_Pct
FROM orders
GROUP BY Region
ORDER BY Total_Sales DESC;


-- ------------------------------------------------------------
-- Q4. Top 10 Customers by Revenue
-- High-value customer identification for CRM and retention.
-- ------------------------------------------------------------
SELECT
    Customer_ID,
    Customer_Name,
    Segment,
    ROUND(SUM(Sales), 2)   AS Total_Sales,
    ROUND(SUM(Profit), 2)  AS Total_Profit,
    COUNT(DISTINCT Order_ID) AS Orders
FROM orders
GROUP BY Customer_ID, Customer_Name, Segment
ORDER BY Total_Sales DESC
LIMIT 10;


-- ------------------------------------------------------------
-- Q5. Top 10 Products by Profit
-- Focus retention and promotion on the most profitable SKUs.
-- ------------------------------------------------------------
SELECT
    Product_ID,
    Product_Name,
    Category,
    Sub_Category,
    ROUND(SUM(Sales), 2)                         AS Total_Sales,
    ROUND(SUM(Profit), 2)                        AS Total_Profit,
    ROUND(SUM(Profit) / SUM(Sales) * 100, 2)     AS Profit_Margin_Pct
FROM orders
GROUP BY Product_ID, Product_Name, Category, Sub_Category
ORDER BY Total_Profit DESC
LIMIT 10;


-- ------------------------------------------------------------
-- Q6. Loss-Making Sub-Categories
-- Identifies sub-categories where total profit is negative.
-- ------------------------------------------------------------
SELECT
    Category,
    Sub_Category,
    ROUND(SUM(Sales), 2)                         AS Total_Sales,
    ROUND(SUM(Profit), 2)                        AS Total_Profit,
    ROUND(SUM(Profit) / SUM(Sales) * 100, 2)     AS Profit_Margin_Pct
FROM orders
GROUP BY Category, Sub_Category
HAVING Total_Profit < 0
ORDER BY Total_Profit ASC;


-- ------------------------------------------------------------
-- Q7. Average Discount by Category
-- High discounts are a key driver of margin compression.
-- ------------------------------------------------------------
SELECT
    Category,
    ROUND(AVG(Discount) * 100, 2)   AS Avg_Discount_Pct,
    ROUND(SUM(Sales), 2)            AS Total_Sales,
    ROUND(SUM(Profit), 2)           AS Total_Profit
FROM orders
GROUP BY Category
ORDER BY Avg_Discount_Pct DESC;


-- ------------------------------------------------------------
-- Q8. Sales and Profit by Customer Segment
-- How do Consumer, Corporate, and Home Office compare?
-- ------------------------------------------------------------
SELECT
    Segment,
    ROUND(SUM(Sales), 2)                         AS Total_Sales,
    ROUND(SUM(Profit), 2)                        AS Total_Profit,
    COUNT(DISTINCT Customer_ID)                  AS Customers,
    COUNT(DISTINCT Order_ID)                     AS Orders,
    ROUND(SUM(Profit) / SUM(Sales) * 100, 2)     AS Profit_Margin_Pct
FROM orders
GROUP BY Segment
ORDER BY Total_Sales DESC;


-- ------------------------------------------------------------
-- Q9. High-Sales, Low-Profit Products
-- Products generating significant revenue but poor margins
-- (Sales > $1000, Profit Margin < 5%) — worthy of review.
-- ------------------------------------------------------------
SELECT
    Product_Name,
    Category,
    Sub_Category,
    ROUND(SUM(Sales), 2)                         AS Total_Sales,
    ROUND(SUM(Profit), 2)                        AS Total_Profit,
    ROUND(SUM(Profit) / SUM(Sales) * 100, 2)     AS Profit_Margin_Pct
FROM orders
GROUP BY Product_Name, Category, Sub_Category
HAVING Total_Sales > 1000
   AND Profit_Margin_Pct < 5
ORDER BY Total_Sales DESC
LIMIT 20;


-- ------------------------------------------------------------
-- Q10. Yearly Performance Summary
-- Year-over-year sales and profit trend.
-- ------------------------------------------------------------
SELECT
    strftime('%Y', Order_Date)  AS Year,
    ROUND(SUM(Sales), 2)        AS Total_Sales,
    ROUND(SUM(Profit), 2)       AS Total_Profit,
    COUNT(DISTINCT Order_ID)    AS Orders,
    COUNT(DISTINCT Customer_ID) AS Customers
FROM orders
GROUP BY Year
ORDER BY Year;


-- ------------------------------------------------------------
-- Q11. Ship Mode Analysis
-- Which shipping modes are most used and what is avg ship time?
-- ------------------------------------------------------------
SELECT
    Ship_Mode,
    COUNT(DISTINCT Order_ID)     AS Orders,
    ROUND(SUM(Sales), 2)         AS Total_Sales,
    ROUND(AVG(Days_to_Ship), 1)  AS Avg_Days_to_Ship
FROM orders
GROUP BY Ship_Mode
ORDER BY Orders DESC;


-- ------------------------------------------------------------
-- Q12. State-level Profitability (top 15 by sales)
-- Supports regional deep-dive and territory management.
-- ------------------------------------------------------------
SELECT
    State,
    Region,
    ROUND(SUM(Sales), 2)                         AS Total_Sales,
    ROUND(SUM(Profit), 2)                        AS Total_Profit,
    ROUND(SUM(Profit) / SUM(Sales) * 100, 2)     AS Profit_Margin_Pct
FROM orders
GROUP BY State, Region
ORDER BY Total_Sales DESC
LIMIT 15;


-- ============================================================
-- END OF business_analysis.sql
-- ============================================================
